<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_UT</name>
   <tag></tag>
   <elementGuidId>8a673083-e23b-4018-a2bd-09e2f5d6d89c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='userActionsMenuHeaderButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userActionsMenuHeaderButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84b2ddc2-80f5-49d2-b50c-8b3fa2f95955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userActionsMenuHeaderButton</value>
      <webElementGuid>7d51689d-9cb6-4755-992e-a1dede0a6fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>userActionsMenuHeaderButton</value>
      <webElementGuid>aa255afc-a530-4582-a8d8-8cf820294923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>454e9455-980d-48b2-9084-aac810a8d484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3eb29622-e777-4d8a-8ade-1c2c3124f2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Profile of USER4653 Trial</value>
      <webElementGuid>a6c594f7-c22f-4939-b50b-cf8509bed644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Profile of USER4653 Trial</value>
      <webElementGuid>497da5a6-6467-46ea-b39e-fa8078059585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>ee64f73e-70c5-4224-8925-af1cca8f65c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapFAvatar sapFAvatarColorAccent6 sapFAvatarXS sapFAvatarInitials sapFAvatarCircle sapMPointer sapFAvatarFocusable</value>
      <webElementGuid>27054471-dfbb-47c7-b755-d2e1556d9aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UT</value>
      <webElementGuid>fba04f5d-5cbf-4296-8f90-8dfd93f4d6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userActionsMenuHeaderButton&quot;)</value>
      <webElementGuid>1083c432-29d1-48e7-8917-8550f615de54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='userActionsMenuHeaderButton']</value>
      <webElementGuid>15567378-97bc-4a22-9b3e-8159cfc9b7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shell-header-hdr-end']/span</value>
      <webElementGuid>f0cb643a-0297-409b-815b-2a60dd994c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::span[1]</value>
      <webElementGuid>c1990c8a-86b6-4fae-bd72-3147d5e02cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::span[2]</value>
      <webElementGuid>9cc188b4-9eb7-4ae6-a1b1-abd2c4ef9014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalize Navigation Bar'])[1]/preceding::span[4]</value>
      <webElementGuid>a46daf7b-84ef-4771-90b3-74544132b837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>b327c685-6524-41b7-9073-f05515dd14e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'userActionsMenuHeaderButton' and @title = 'Profile of USER4653 Trial' and (text() = 'UT' or . = 'UT')]</value>
      <webElementGuid>381949c9-fb87-4aba-9838-ca29d7fa7728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
