<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SaveEmphasized</name>
   <tag></tag>
   <elementGuidId>7343fefe-865b-4a0e-a377-d95337fe58ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:50::btn[11]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed3f731f-ed7b-42cc-8f9b-dc17999b38f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>13a50bad-8d3b-464c-9701-f8eea1e5eacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:50::btn[11]</value>
      <webElementGuid>c009101c-c062-4051-a70c-ae37f65d3d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>511a36bd-fec9-4e02-a8ad-729b91c7d496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Save&quot;,&quot;2&quot;:&quot;EMPHASIZED&quot;,&quot;4&quot;:&quot;Save (Cmd S)&quot;,&quot;18&quot;:&quot;S&quot;,&quot;19&quot;:&quot;CTRL_S&quot;,&quot;22&quot;:true,&quot;26&quot;:&quot;TOGGLE&quot;,&quot;28&quot;:{&quot;SID&quot;:&quot;wnd[0]/tbar[0]/btn[11]&quot;,&quot;Type&quot;:&quot;GuiButton&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>9611d87a-3305-47dd-8c19-f61ec2173455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;1&quot;:&quot;action/3&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>09599067-ad93-4e84-a7f9-91c29168e23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint</name>
      <type>Main</type>
      <value>{&quot;WebAssistant&quot;:{&quot;id&quot;:{&quot;id&quot;:&quot;wnd[0]/tbar[0]/btn[11]&quot;,&quot;dynp&quot;:&quot;SAPMV45A:4001:VA02&quot;}}}</value>
      <webElementGuid>ba03153b-8e69-4bd3-9dcd-15bd8105c3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0eceade-3a43-4623-8db2-85e3fc0c4a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save (Cmd S)</value>
      <webElementGuid>c7190b96-1458-4a8e-aaea-76d76fd85bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>dcfc6b72-c2ef-48eb-ab47-6f645304929a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>f5ee92f7-6622-455b-a97d-1829d812249a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cded405f-85a1-4e5c-ad18-8fcd948471de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2de90d92-a93d-41a8-804c-d017564b6211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urInlineMetricTop urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-emphasized lsButton--hoverable</value>
      <webElementGuid>5bae61e8-5862-4f8f-8698-ae2c02463af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>M0:50::btn[11]-r</value>
      <webElementGuid>b0d2ad9e-d86b-42cd-aab2-26f705d5091d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Emphasized</value>
      <webElementGuid>80d8dd44-af3f-492f-8efd-d84858b9cfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:50::btn[11]&quot;)</value>
      <webElementGuid>6f961cab-2156-4639-aa92-1ffa90555e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Change Standard Order 183427 Overview/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>e25aad52-ea5b-4e11-af9e-5615862febc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:50::btn[11]']</value>
      <webElementGuid>8069a3ee-66de-4dc9-9383-812f4fe4e289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:50::btn[11]-r']/div</value>
      <webElementGuid>a2ee87ca-f8a9-469c-8824-e5306e8fdfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Bar'])[1]/following::div[1]</value>
      <webElementGuid>49b2602f-2b58-40d5-b0c3-d717fea9d528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[4]/following::div[11]</value>
      <webElementGuid>9c9b7b73-a4e4-46ff-b55b-badf38a017ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]/div</value>
      <webElementGuid>71962bad-de3c-4502-a99c-ad2b5b99150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:50::btn[11]' and @title = 'Save (Cmd S)' and (text() = 'Save Emphasized' or . = 'Save Emphasized')]</value>
      <webElementGuid>aef781d6-9edf-41c6-bb6d-cc42fc686b3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
