<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Req. Deliv.DateDeliver.PlantComplete Dl_729c15</name>
   <tag></tag>
   <elementGuidId>dca1ef86-18e0-4abe-9636-c34e4610cfdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:2:3B256:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2e35237-73dd-443f-97a4-9bb717b80dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2:3B256:1</value>
      <webElementGuid>0974e1e0-6610-42bc-87ca-00b3fe83e26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>RL</value>
      <webElementGuid>999f3002-a8e6-4aa8-bfb6-cb61417958d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:4.00,&quot;2&quot;:1.25,&quot;4&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440&quot;,&quot;Type&quot;:&quot;GuiScrollContainer&quot;},&quot;6&quot;:&quot;AUTO&quot;}</value>
      <webElementGuid>74750ae0-17f4-4e78-b1da-b93dd8fca9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Scroll&quot;:[{},{}]}</value>
      <webElementGuid>9ba42345-5102-40c0-8259-10c7705a7e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bnoposrefcontainer</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>200c6592-5d39-49e7-b3a8-5898c602ff5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>564c5ca0-1145-41cf-8c46-c4a854386513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsRasterLayout  lsRL--relative lsRL--scrollingmode-auto</value>
      <webElementGuid>7c7dd5fa-6df7-44bc-b763-f65ceeb8d7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Req. Deliv.DateDeliver.Plant:Complete Dlv.Total WeightDelivery BlockVolumeBilling BlockPricing DatePyt TermsAs of End of MonthInco. VersionIncotermsInco. Location1Inco. Location2Order ReasonSales Area//Dom. Sales Org US, Direct Sales, Product Division 00</value>
      <webElementGuid>a2f99cfe-7d9f-4b1c-b565-78abe0eecc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2:3B256:1&quot;)</value>
      <webElementGuid>eb80c1fa-9cce-4737-9e8d-cff94ba84e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Change Standard Order 183427 Overview/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>366cdf9a-2668-40d0-9eb8-3f17a3b86335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2:3B256:1']</value>
      <webElementGuid>8be8998c-dd9e-401d-85ac-a1b10417a86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u3546']/div</value>
      <webElementGuid>097b8d14-8912-41fa-8886-ff3bf608e5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason for Rejection'])[1]/following::div[7]</value>
      <webElementGuid>e8d90bec-96a6-4d24-89e0-485860562b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping'])[1]/following::div[10]</value>
      <webElementGuid>5a0a8d66-d057-48c8-912b-2dfbfecfb73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/div/div/div/div/div</value>
      <webElementGuid>7e7b5371-c15f-4434-b619-127c50fda633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:2:3B256:1' and (text() = 'Req. Deliv.DateDeliver.Plant:Complete Dlv.Total WeightDelivery BlockVolumeBilling BlockPricing DatePyt TermsAs of End of MonthInco. VersionIncotermsInco. Location1Inco. Location2Order ReasonSales Area//Dom. Sales Org US, Direct Sales, Product Division 00' or . = 'Req. Deliv.DateDeliver.Plant:Complete Dlv.Total WeightDelivery BlockVolumeBilling BlockPricing DatePyt TermsAs of End of MonthInco. VersionIncotermsInco. Location1Inco. Location2Order ReasonSales Area//Dom. Sales Org US, Direct Sales, Product Division 00')]</value>
      <webElementGuid>f17324aa-7202-4076-aea7-0b984af578a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
