<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_183427</name>
   <tag></tag>
   <elementGuidId>14091d5f-911a-4a7e-9452-f5c1d1e7b29f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__identifier3-__clone201-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Date'])[2]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>418ebac5-9654-4086-b6ed-2727d33da3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier3-__clone201-link</value>
      <webElementGuid>6c7ad3d6-c950-4961-a679-03cb01237577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__identifier3-__clone201-link</value>
      <webElementGuid>5cfecf44-d457-4df0-a9c0-2c2dc57eabbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>0fd8bd25-4f33-44de-b81d-d7ec5fa25c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3055e1f7-2626-43a3-be4b-a0182ec0a2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__text82 __identifier3-__clone201-text cus.sd.salesorders.manage::sap.suite.ui.generic.template.ListReport.view.ListReport::C_SalesOrderWl_F1873--listReport-SalesOrder-header __identifier3-__clone201-link</value>
      <webElementGuid>e7c0fa4f-e27e-4aa5-9917-2a2b8f64b021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth</value>
      <webElementGuid>78bb5222-47e2-484d-80ea-90033c488659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>183427</value>
      <webElementGuid>6b285017-2eb2-4eb6-8185-c701708d557f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier3-__clone201-link&quot;)</value>
      <webElementGuid>8b4d9480-d5cc-4e28-9e1f-990179a93faa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='__identifier3-__clone201-link']</value>
      <webElementGuid>c24b3691-569c-46c3-ae17-7f58110107f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier3-__clone201-title']/a</value>
      <webElementGuid>512fb869-a055-42b3-ba03-b86c4f14705d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'183427')]</value>
      <webElementGuid>8218995f-53ff-4b14-8d0b-4ac82e4d736e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Date'])[2]/following::a[1]</value>
      <webElementGuid>377f95c6-9836-44cc-8803-1e31081e31f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net Value'])[1]/following::a[1]</value>
      <webElementGuid>eec760e2-27d0-45e0-8041-1eca12105fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barrel &amp; Son Corp. (17100007)'])[1]/preceding::a[1]</value>
      <webElementGuid>b3cfb1b1-f6dd-447a-af31-b724ea4fa574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST'])[1]/preceding::a[2]</value>
      <webElementGuid>4bd1489c-db4e-4600-bd5c-831bbaee3080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>4257ea33-8db2-4cd4-9a04-fe6722f4b6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>e8e55481-f2fa-4cd7-9edb-2aa54f1b0c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '__identifier3-__clone201-link' and @href = 'javascript:void(0)' and (text() = '183427' or . = '183427')]</value>
      <webElementGuid>c29c976b-0cd1-4e32-b436-15189f9ddcdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
