<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sales Orders - Actuals</name>
   <tag></tag>
   <elementGuidId>12f28ae6-fcf0-4211-a57e-ad6bd7395043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__link183</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='__link183']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb483ff8-dd1f-4784-902b-675313c39b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__link183</value>
      <webElementGuid>ac5a542e-8409-42a7-9cb1-ad93794e795a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__link183</value>
      <webElementGuid>8e7cbec4-a697-4ac4-b80f-192adfc43b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#SalesOrder-analyzeActualsPC?%2524.basicSearch=&amp;Customer=17100007&amp;DeliveryBlockReason=&amp;DistributionChannel=10&amp;HeaderBillingBlockReason=&amp;OrganizationDivision=00&amp;PurchaseOrderByCustomer=TEST&amp;RequestedDeliveryDate=2023-04-25T00%253A00%253A00.000Z&amp;SalesOrder=183427&amp;SalesOrderDate=2023-04-25T00%253A00%253A00.000Z&amp;SalesOrganization=1710&amp;SoldToPartyName=Barrel%2520%2526%2520Son%2520Corp.&amp;TotalNetAmount=26800.00&amp;TransactionCurrency=USD&amp;sap-app-origin-hint=&amp;sap-xapp-state=ASQ2DU8QIT4ZR8L22VZV2Z50K9160SM38NGCYBYZ</value>
      <webElementGuid>21e2b44f-99ba-407c-aed9-39fb9a437e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4578f59c-41d6-4cc7-bc77-cac0beadd11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth</value>
      <webElementGuid>6e5dc7bb-e81e-4639-9158-65fe90ab26d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales Orders - Actuals</value>
      <webElementGuid>d37352fa-685c-47a8-837e-dd3553508aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__link183&quot;)</value>
      <webElementGuid>ccc977be-eee3-44c7-8b28-a585e4a570dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='__link183']</value>
      <webElementGuid>f86e4be3-3a82-4370-840f-d850422dd455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__data2838']/a</value>
      <webElementGuid>e1ff8b13-5660-440c-abb2-e0077490c525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sales Orders - Actuals')]</value>
      <webElementGuid>ca97bad3-3cb5-486f-914d-948e93bad004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Order'])[1]/following::a[1]</value>
      <webElementGuid>24f0fefe-ac92-4715-bdf4-18cf0c866590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter'])[1]/following::a[2]</value>
      <webElementGuid>195e0573-1ecf-4970-89ce-d3f383da40be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Links'])[1]/preceding::a[1]</value>
      <webElementGuid>387d2e0d-9270-42ff-bce6-9fc23699e164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::a[1]</value>
      <webElementGuid>0ee5628d-69b8-4e30-af3a-e6b1c58dd84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#SalesOrder-analyzeActualsPC?%2524.basicSearch=&amp;Customer=17100007&amp;DeliveryBlockReason=&amp;DistributionChannel=10&amp;HeaderBillingBlockReason=&amp;OrganizationDivision=00&amp;PurchaseOrderByCustomer=TEST&amp;RequestedDeliveryDate=2023-04-25T00%253A00%253A00.000Z&amp;SalesOrder=183427&amp;SalesOrderDate=2023-04-25T00%253A00%253A00.000Z&amp;SalesOrganization=1710&amp;SoldToPartyName=Barrel%2520%2526%2520Son%2520Corp.&amp;TotalNetAmount=26800.00&amp;TransactionCurrency=USD&amp;sap-app-origin-hint=&amp;sap-xapp-state=ASQ2DU8QIT4ZR8L22VZV2Z50K9160SM38NGCYBYZ')]</value>
      <webElementGuid>a159725f-1730-419f-9957-1aa00b4098fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>770a39e6-7b70-4719-a6e7-edd24d1470e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '__link183' and @href = '#SalesOrder-analyzeActualsPC?%2524.basicSearch=&amp;Customer=17100007&amp;DeliveryBlockReason=&amp;DistributionChannel=10&amp;HeaderBillingBlockReason=&amp;OrganizationDivision=00&amp;PurchaseOrderByCustomer=TEST&amp;RequestedDeliveryDate=2023-04-25T00%253A00%253A00.000Z&amp;SalesOrder=183427&amp;SalesOrderDate=2023-04-25T00%253A00%253A00.000Z&amp;SalesOrganization=1710&amp;SoldToPartyName=Barrel%2520%2526%2520Son%2520Corp.&amp;TotalNetAmount=26800.00&amp;TransactionCurrency=USD&amp;sap-app-origin-hint=&amp;sap-xapp-state=ASQ2DU8QIT4ZR8L22VZV2Z50K9160SM38NGCYBYZ' and (text() = 'Sales Orders - Actuals' or . = 'Sales Orders - Actuals')]</value>
      <webElementGuid>f26c01b1-c392-44f6-a396-1426d4e95fe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
