<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Leave Tour</name>
   <tag></tag>
   <elementGuidId>247d93f0-7e71-4c14-b170-fe4cc84e0751</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@title = 'Leave Tour' and @role = 'button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__75I88VMGRB2SWM2WGEOYV56N-cl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__75I88VMGRB2SWM2WGEOYV56N-cl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1bca914e-eada-4570-b0a9-f0b409bb1f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__75I88VMGRB2SWM2WGEOYV56N-cl</value>
      <webElementGuid>b6c5cd2a-a722-4391-947a-6d62ac3500c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Leave Tour</value>
      <webElementGuid>1156965b-7f8d-4f62-9a9f-a2ce53d0d3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a1649d5-b8e9-44d3-b6d2-1ef7f13849ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Leave Tour</value>
      <webElementGuid>f8ee1900-c62a-4fa6-942d-c86d8fa380a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-close help4-control-button help4-control help4-icon</value>
      <webElementGuid>68e44f5b-deb3-4122-be06-bde0500ff0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>106f2ce9-4d4e-4813-96f5-75382c45022c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__75I88VMGRB2SWM2WGEOYV56N-cl&quot;)</value>
      <webElementGuid>b25cdfc9-1a6e-438f-901d-8cbf0ef600db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='__75I88VMGRB2SWM2WGEOYV56N-cl']</value>
      <webElementGuid>bf353042-b7ba-4604-a847-21ae4b2579e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__75I88VMGRB2SWM2WGEOYV56N']/header/button</value>
      <webElementGuid>749d8834-430b-4e56-ab5f-d6e905e8f89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[2]/following::button[2]</value>
      <webElementGuid>c97253ed-06d2-4ac9-9fe8-c10c118e2fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to SAP S/4HANA Cloud Public Edition!'])[1]/preceding::button[1]</value>
      <webElementGuid>7680b5d9-6fe5-4c89-9abd-0b2b08b97e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Some important details about this trial:'])[1]/preceding::button[1]</value>
      <webElementGuid>e62b55ac-f7a1-4efe-a697-6a1d6e2d7af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/button</value>
      <webElementGuid>cd7c5082-28d8-4dd5-8784-7faa3445b68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '__75I88VMGRB2SWM2WGEOYV56N-cl' and @title = 'Leave Tour' and (text() = '' or . = '')]</value>
      <webElementGuid>cc48113a-c91b-49c6-b579-cd57d3468a0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
