<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sales Orders (1)StandardSelect ViewCrea_4224ff</name>
   <tag></tag>
   <elementGuidId>e0eebe7c-9820-4e6b-8952-f7745f67d00e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cus.sd.salesorders.manage::sap.suite.ui.generic.template.ListReport.view.ListReport::C_SalesOrderWl_F1873--page-contentFitContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>619bc26b-8537-414f-8a93-57dc60b8b636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorders.manage::sap.suite.ui.generic.template.ListReport.view.ListReport::C_SalesOrderWl_F1873--page-contentFitContainer</value>
      <webElementGuid>7eac3d89-503c-4e1b-b7f2-67028bb4add5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapFDynamicPageContentFitContainer</value>
      <webElementGuid>25c0ba41-261b-4e0f-b4be-b16e19b970e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales Orders (1)StandardSelect ViewCreateCreate with ReferenceReject All ItemsSet Delivery BlockRemove Delivery BlockSet Billing BlockAdditional optionsSales OrderSold-to PartyCustomer ReferenceRequested Delivery DateOverall StatusNet ValueDocument Date183427Barrel &amp; Son Corp. (17100007)TEST04/25/2023Open26,800.00 USD04/25/2023More</value>
      <webElementGuid>36c83db5-8867-417a-a454-a2d0567da315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorders.manage::sap.suite.ui.generic.template.ListReport.view.ListReport::C_SalesOrderWl_F1873--page-contentFitContainer&quot;)</value>
      <webElementGuid>219e77e7-039d-40d9-ac9d-1fad75af2c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorders.manage::sap.suite.ui.generic.template.ListReport.view.ListReport::C_SalesOrderWl_F1873--page-contentFitContainer']</value>
      <webElementGuid>caaf8fdf-606c-4378-90b4-22d9ce085570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorders.manage::sap.suite.ui.generic.template.ListReport.view.ListReport::C_SalesOrderWl_F1873--page-content']/div</value>
      <webElementGuid>7b30e15c-a68b-4be0-adcc-102466aab779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pin Header'])[1]/following::div[2]</value>
      <webElementGuid>906cfe31-4178-4fc8-9b92-6fb316f29acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse Header'])[1]/following::div[2]</value>
      <webElementGuid>8c1b64ec-abec-4d07-8ff4-b3b69bdf4c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div[2]/div</value>
      <webElementGuid>3acce8ed-5f52-490e-93b2-4a124f5e98fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cus.sd.salesorders.manage::sap.suite.ui.generic.template.ListReport.view.ListReport::C_SalesOrderWl_F1873--page-contentFitContainer' and (text() = 'Sales Orders (1)StandardSelect ViewCreateCreate with ReferenceReject All ItemsSet Delivery BlockRemove Delivery BlockSet Billing BlockAdditional optionsSales OrderSold-to PartyCustomer ReferenceRequested Delivery DateOverall StatusNet ValueDocument Date183427Barrel &amp; Son Corp. (17100007)TEST04/25/2023Open26,800.00 USD04/25/2023More' or . = 'Sales Orders (1)StandardSelect ViewCreateCreate with ReferenceReject All ItemsSet Delivery BlockRemove Delivery BlockSet Billing BlockAdditional optionsSales OrderSold-to PartyCustomer ReferenceRequested Delivery DateOverall StatusNet ValueDocument Date183427Barrel &amp; Son Corp. (17100007)TEST04/25/2023Open26,800.00 USD04/25/2023More')]</value>
      <webElementGuid>f2dc184b-27a6-466f-b36e-92a4eed05e3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
