<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sales OrderContains 1 token183427Sold-t_9beef2</name>
   <tag></tag>
   <elementGuidId>a8d83709-378a-4c5a-98b9-912b63bf3fc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__layout201</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand Header'])[1]/following::div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40b724b5-86cb-4009-9dcb-e05bddb9cfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__layout201</value>
      <webElementGuid>3c88f22c-3bba-4429-a5fc-c0c9fa39cf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__layout201</value>
      <webElementGuid>ca48baaf-5a60-461d-a2b1-6762f1166ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiAFLayout</value>
      <webElementGuid>4ba32c14-43f2-4d11-8f8a-b0f10f291735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sales OrderContains 1 token =183427Sold-to PartyNo tokensCustomer ReferenceRequested Delivery DateOverall StatusNo tokensSelect OptionsDocument DateSales OrganizationContains 1 token Dom. Sales Org US (1710)Distribution ChannelContains 1 token Direct Sales (10)DivisionContains 1 token Product Division 00 (00)GoAdapt Filters (4)</value>
      <webElementGuid>5bfd138e-9935-499c-970e-8d86451589a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout201&quot;)</value>
      <webElementGuid>399c1a4a-cfb4-4c81-aec7-959171e8b1d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__layout201']</value>
      <webElementGuid>55399975-485d-4ddf-a419-bdaca2a67047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorders.manage::sap.suite.ui.generic.template.ListReport.view.ListReport::C_SalesOrderWl_F1873--listReportFilter-wrapperfor-__layout201']/div</value>
      <webElementGuid>2c715796-482b-4abf-9d0c-08ee2a078c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand Header'])[1]/following::div[7]</value>
      <webElementGuid>07bb1aa0-1cdf-4665-b912-9ae398804a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtered By (4): Sales Order, Sales Organization, Distribution Channel, Division'])[1]/following::div[7]</value>
      <webElementGuid>0169ea02-d82e-4bba-864d-4e91f1e9dab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/section/div/div/div/div</value>
      <webElementGuid>13290872-be82-4a0e-b8c5-e76a30ec7ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__layout201' and (text() = ' Sales OrderContains 1 token =183427Sold-to PartyNo tokensCustomer ReferenceRequested Delivery DateOverall StatusNo tokensSelect OptionsDocument DateSales OrganizationContains 1 token Dom. Sales Org US (1710)Distribution ChannelContains 1 token Direct Sales (10)DivisionContains 1 token Product Division 00 (00)GoAdapt Filters (4)' or . = ' Sales OrderContains 1 token =183427Sold-to PartyNo tokensCustomer ReferenceRequested Delivery DateOverall StatusNo tokensSelect OptionsDocument DateSales OrganizationContains 1 token Dom. Sales Org US (1710)Distribution ChannelContains 1 token Direct Sales (10)DivisionContains 1 token Product Division 00 (00)GoAdapt Filters (4)')]</value>
      <webElementGuid>a1a593d0-78ca-4987-9ba4-a0828c63e213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
