<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_183427</name>
   <tag></tag>
   <elementGuidId>be122917-3486-4fa1-b388-e418fd9493de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__identifier3-__clone201-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Date'])[2]/following::div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10d6d67a-3b2a-46af-911a-6ea14d517e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier3-__clone201-title</value>
      <webElementGuid>da8193b5-c7d3-4b04-acef-bc26257235ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMObjectIdentifierTitle</value>
      <webElementGuid>9c25ccbe-d777-475c-a9f9-8abd35886648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>183427</value>
      <webElementGuid>2cc7ec27-24ca-48e9-afd4-47d15624ea56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier3-__clone201-title&quot;)</value>
      <webElementGuid>6c537179-1e9a-48f9-9a14-9709f1655c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__identifier3-__clone201-title']</value>
      <webElementGuid>d1103380-63f6-4312-b7b1-11aeb7506cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier3-__clone201']/div/div</value>
      <webElementGuid>1f86c0ff-7d25-45f7-a1f9-c02d9f812061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Date'])[2]/following::div[5]</value>
      <webElementGuid>5618f349-438b-4459-ac2d-f85de9c6d00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net Value'])[1]/following::div[6]</value>
      <webElementGuid>6559c367-3080-4141-9eb9-17b5d74cae52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barrel &amp; Son Corp. (17100007)'])[1]/preceding::div[3]</value>
      <webElementGuid>d0676db1-a8f5-4bb1-8122-21969caf0e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST'])[1]/preceding::div[3]</value>
      <webElementGuid>bac7b28d-7dd7-4e8c-b4ea-6867341c4e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div</value>
      <webElementGuid>bfe6d386-7e44-4141-bfa5-6d7222bca9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__identifier3-__clone201-title' and (text() = '183427' or . = '183427')]</value>
      <webElementGuid>8eebb5bf-92cf-4e01-87ee-30538e1fdc95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
