<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create Sales Order VA01</name>
   <tag></tag>
   <elementGuidId>d4a3bd2a-757f-492d-8a17-ca063582bfdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-SalesOrder-manage-component---id-1553605021678-105-originalButtonId-unifiedmenu-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application-SalesOrder-manage-component---id-1553605021678-105-originalButtonId-unifiedmenu-txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ab8f2e9-9926-4e38-a7b7-b01d58cb3ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-SalesOrder-manage-component---id-1553605021678-105-originalButtonId-unifiedmenu-txt</value>
      <webElementGuid>a56dbc13-a581-4688-8c9f-e3199ac2a2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiMnuItmTxt</value>
      <webElementGuid>2bcb11bd-e57d-47ab-8c19-b61c0d372f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Sales Order VA01</value>
      <webElementGuid>a1800774-e832-49ee-b9ff-8619a2917679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-SalesOrder-manage-component---id-1553605021678-105-originalButtonId-unifiedmenu-txt&quot;)</value>
      <webElementGuid>4e58aced-ecf3-4cc2-9f1b-79624c33f65f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='application-SalesOrder-manage-component---id-1553605021678-105-originalButtonId-unifiedmenu-txt']</value>
      <webElementGuid>e23724bd-39f6-4bd3-80c7-95b5f6a96000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='application-SalesOrder-manage-component---id-1553605021678-105-originalButtonId-unifiedmenu']/div[2]</value>
      <webElementGuid>4206b1cd-b8a2-407a-a08a-8e80c561c2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Sales Order'])[1]/preceding::div[5]</value>
      <webElementGuid>673b9789-8b25-4a38-aedc-4de7c7e30c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[10]</value>
      <webElementGuid>3559eb23-844b-4343-9347-af82a22cf1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Sales Order VA01']/parent::*</value>
      <webElementGuid>4fcf2274-a0b2-47cb-b289-e77d5becde80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]</value>
      <webElementGuid>38138900-1b69-43b8-9754-43f1a4f66725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'application-SalesOrder-manage-component---id-1553605021678-105-originalButtonId-unifiedmenu-txt' and (text() = 'Create Sales Order VA01' or . = 'Create Sales Order VA01')]</value>
      <webElementGuid>9e831662-24bf-4236-8afe-ac0d5c900b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
