<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create</name>
   <tag></tag>
   <elementGuidId>b05d745d-67e7-4d41-86f7-2e02bcb3269c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93a52ebb-9c61-4329-98bd-920fc104d9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner</value>
      <webElementGuid>c1423aec-78a9-47d6-969e-edbcdc9580e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnDefault</value>
      <webElementGuid>baef8cb1-69ee-4ada-a769-ef69a3f88aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>2db71bd1-767e-4b8d-9c6f-f9970368d9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner&quot;)</value>
      <webElementGuid>d153c586-4b73-4525-984c-e0b502cced13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner']</value>
      <webElementGuid>57146697-7dbe-42d1-ad7e-fceef7fa6e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='application-SalesOrder-manage-component---id-1553605021678-103-internalBtn']/span</value>
      <webElementGuid>d20e3aca-f219-45a9-b46e-453ff9fd121c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select View'])[2]/following::span[1]</value>
      <webElementGuid>93f8e627-e64b-469c-b740-140654d68c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard'])[2]/following::span[5]</value>
      <webElementGuid>62e6e146-bc59-4d91-974f-13e5bc0da4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create with Reference'])[1]/preceding::span[2]</value>
      <webElementGuid>691b37c9-1c0c-444c-a6de-0c704d1a1cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button/span</value>
      <webElementGuid>a2f85a0d-8d41-4445-a4c2-f012e3ac3eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>1887c8e1-ac33-45cb-9bf2-8e8b00269c0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
