<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Services for Object</name>
   <tag></tag>
   <elementGuidId>d93c492b-155a-4bf2-9226-eca58f8b0afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='%GOS_TOOLBOX102']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d46f5972-533e-43db-9cd6-b61bfcef025c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5f756095-dc77-42c6-8fe5-5667b65d26f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>%GOS_TOOLBOX102</value>
      <webElementGuid>4314c4b7-a306-4d86-bcb2-56c32a3c0ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>c684f055-c749-447e-a572-6b0d3eb57779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Services for Object&quot;,&quot;4&quot;:&quot;Services for Object&quot;,&quot;14&quot;:true,&quot;18&quot;:&quot;S&quot;,&quot;22&quot;:true,&quot;26&quot;:&quot;TOGGLE&quot;,&quot;28&quot;:{&quot;SID&quot;:&quot;wnd[0]/titl/shellcont/shell/dbtn%GOS_TOOLBOX&quot;,&quot;Type&quot;:&quot;GuiButton&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>21126eb2-f3fa-43c4-8397-26e033a223be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;1&quot;:&quot;action/3&quot;,&quot;2&quot;:true,&quot;3&quot;:true}],&quot;MenuAccess&quot;:[{},{&quot;1&quot;:&quot;action/12&quot;,&quot;2&quot;:true,&quot;3&quot;:true,&quot;dynamic&quot;:true}]}</value>
      <webElementGuid>4c4f5d69-fc05-483d-9698-5a4900472a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c8c1002-a92d-48aa-a1da-5af322ad7550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ae1eeaf-10ab-4a55-af59-e7231d664bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>-r</value>
      <webElementGuid>dcb454c8-330a-4649-919a-ec8fa670eaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Services for Object</value>
      <webElementGuid>c2b6e101-0403-403f-a968-d86f653c3846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>08487370-ec45-4d35-a519-23197443ae84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>dca4dd74-3d38-4cf6-a9b4-16fd1e272e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a152ad81-cb5d-40de-94ee-01311d51d274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1462d50-2422-4ebe-8a84-ab41f954f7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urInlineMetricTop urNoUserSelect urBtnRadius lsButton--popupmenu lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--behaviour-toggle lsButton--design-standard lsButton--hoverable</value>
      <webElementGuid>40a89638-654e-4f85-909e-3a1277904fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>%GOS_TOOLBOX102-r</value>
      <webElementGuid>7f6c9602-4350-4a2d-ba42-6ca48a86e6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services for Object</value>
      <webElementGuid>254da811-61a4-438b-99f3-6d3992f5ecc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;%GOS_TOOLBOX102&quot;)</value>
      <webElementGuid>f804b9e2-5f6b-4a72-a289-bc191be242c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Display Standard Order 183427 Item Data/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>ec80bd5f-4503-47af-9152-540e7d9344b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='%GOS_TOOLBOX102']</value>
      <webElementGuid>b499f9a0-4d3f-4327-a6e9-3029f263daa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='%GOS_TOOLBOX102-r']/div</value>
      <webElementGuid>068a4892-2842-4a9f-8de1-e527bffa8742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[1]/following::div[1]</value>
      <webElementGuid>f075e6cd-fad3-431f-92a5-8e2a12ba7328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/div</value>
      <webElementGuid>7315762b-c0bf-46b6-967f-efd1c5667af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '%GOS_TOOLBOX102' and @title = 'Services for Object' and (text() = 'Services for Object' or . = 'Services for Object')]</value>
      <webElementGuid>af8fadde-dfef-4aae-bd0c-add0419529a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
