<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Structure</name>
   <tag></tag>
   <elementGuidId>8bbc64c1-5d28-48fd-b44c-6c8c7cc5bc62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:2::0:11-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a97d36f8-48b7-4422-8147-d6347a63b2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2::0:11-title</value>
      <webElementGuid>869bbb9e-4a17-4163-b6c1-a0689180a53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>TAB_ACCESS</value>
      <webElementGuid>3f7e7894-ec91-431c-a8d7-45081cf3c194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTbsv5-ItemTitle</value>
      <webElementGuid>0c273434-35ef-4f6b-a90d-a46bd2128fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>dee8ef0d-8803-4842-913b-a9a6719d1b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>23863c98-825a-4b13-a187-156880866ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>eb21dcab-d290-4ef6-8e94-4faef3dc2057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>M0:46:2::0:11-cnt</value>
      <webElementGuid>3154b3db-dcb0-40d2-b93b-de90c620f3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a13e2a3-0198-48f4-87a9-a4d98dd9a1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>74249e4b-6af5-4645-acd0-125bb99c00e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6df7a4c6-0228-47f6-b99a-b7c2088bb851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Structure</value>
      <webElementGuid>55e06de6-5ffa-4420-90ea-7e6a7af0d81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2::0:11-title&quot;)</value>
      <webElementGuid>f847d842-4941-4960-b896-735d1daf6d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Display Standard Order 183427 Item Data/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>56ef033b-9b14-41d8-a47e-c6bd2713be9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2::0:11-title']</value>
      <webElementGuid>637e55a7-f98a-45a4-97c8-d91ee9df2581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2::0:11']/div</value>
      <webElementGuid>04bf9624-1fda-4c81-8a3a-fabdb040356d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[3]</value>
      <webElementGuid>75587a65-83e6-4360-9c7a-a68c465b64a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Data'])[1]/following::div[6]</value>
      <webElementGuid>f96cfe0f-d14f-4cde-954e-19066785707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional data A'])[1]/preceding::div[2]</value>
      <webElementGuid>1caa2cd0-3d8a-447f-a83a-3174cb413bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional data B'])[1]/preceding::div[5]</value>
      <webElementGuid>61756966-dbb9-4672-8acb-cda0a6b44ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div</value>
      <webElementGuid>3893b3d8-6eac-439c-b196-96c9747d0ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:2::0:11-title' and (text() = 'Structure' or . = 'Structure')]</value>
      <webElementGuid>ff07dba0-bd7f-4033-8508-915914cb2200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
