<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sales ASales ASales BSales BShippingShi_5ed583</name>
   <tag></tag>
   <elementGuidId>afbfe735-0065-4c2d-87d0-a0c97ed9ab1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:2-panel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e14f257d-9ae8-4d87-afc5-8c5dd6ba1fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolltoprevious</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>75a9083a-1a01-4783-9b9b-89320e558009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2-panel</value>
      <webElementGuid>517bafba-da64-4627-a2c4-9e58ca4bd392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTbsOvfl lsTbsPanelsWidth</value>
      <webElementGuid>43f9504d-f210-4ec5-b9dd-c2371066a041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tablist</value>
      <webElementGuid>b4568809-e87f-49ae-90f9-2c12b20c64a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>M0:46:2::0:11</value>
      <webElementGuid>12803850-eed4-4983-bc7b-8a0b2d665bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>M0:46:2::0:0 M0:46:2::0:1 M0:46:2::0:2 M0:46:2::0:3 M0:46:2::0:4 M0:46:2::0:5 M0:46:2::0:6 M0:46:2::0:7 M0:46:2::0:8 M0:46:2::0:9 M0:46:2::0:10 M0:46:2::0:11 M0:46:2::0:12 M0:46:2::0:13 </value>
      <webElementGuid>9e2555a8-c804-4849-896d-1c60080b1e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales ASales ASales BSales BShippingShippingBilling DocumentBilling DocumentConditionsConditionsAccount assignmentAccount assignmentSchedule LinesSchedule LinesPartnerPartnerTextsTextsOrder DataOrder DataStatusStatusStructureStructureAdditional data AAdditional data AAdditional data BAdditional data B</value>
      <webElementGuid>209c8281-a8b2-465a-bba5-fe20c9861456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2-panel&quot;)</value>
      <webElementGuid>e85a2ef3-d6ae-4180-b688-8179b12f22b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Display Standard Order 183427 Item Data/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>0b006554-acd4-4e6e-8bc5-10882d82481c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2-panel']</value>
      <webElementGuid>6618968a-8560-482a-939c-1842c83686b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:2']/tbody/tr/td/table/tbody/tr/td[2]/div</value>
      <webElementGuid>fd01958f-79d5-4f41-ba15-accf41878353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', '26', '&quot;', '', '&quot;', ' In-Home Exercise Bike', '&quot;', '')])[2]/following::div[2]</value>
      <webElementGuid>b476b025-149e-4f9e-ad5b-a5c3940cb982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', '26', '&quot;', '', '&quot;', ' In-Home Exercise Bike', '&quot;', '')])[1]/following::div[3]</value>
      <webElementGuid>5b097766-2dde-4b23-ba66-93ea3c39f0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>15ac849c-51be-468e-a0cc-8c844f27a717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:2-panel' and (text() = 'Sales ASales ASales BSales BShippingShippingBilling DocumentBilling DocumentConditionsConditionsAccount assignmentAccount assignmentSchedule LinesSchedule LinesPartnerPartnerTextsTextsOrder DataOrder DataStatusStatusStructureStructureAdditional data AAdditional data AAdditional data BAdditional data B' or . = 'Sales ASales ASales BSales BShippingShippingBilling DocumentBilling DocumentConditionsConditionsAccount assignmentAccount assignmentSchedule LinesSchedule LinesPartnerPartnerTextsTextsOrder DataOrder DataStatusStatusStructureStructureAdditional data AAdditional data AAdditional data BAdditional data B')]</value>
      <webElementGuid>22a0575f-425b-469b-be58-0e077b410c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
