<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(, , undefined, , )_applicatio_2e7af2</name>
   <tag></tag>
   <elementGuidId>ebb64728-b6b8-401b-baa9-28fc4952f0a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-SalesOrder-create-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-SalesOrder-create-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>df1525d9-49f4-48ce-a58f-d81b5ce1ea45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>ca3c3ea7-a9ad-4997-9832-5134a61053f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>f852ad03-95e9-4747-8c80-0a31d81a3e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>bde9c1e9-6382-45ed-ae1f-8fca7f02be38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=T04;~service=3200?~transaction=%2AVAX1_VBTYP+DYNP_OKCODE%3DENT2%3BP_TRVOG%3D0%3BP_VBTYP%3DC&amp;sap-client=100&amp;sap-language=EN&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=sap_horizon_dark&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-touch=0&amp;sap-ushell-timeout=0&amp;sap-shell=FLP1.102.12</value>
      <webElementGuid>31eb26ae-dbc0-45fc-9725-bca683bfca2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>372d2944-46e6-49dc-9222-3971077de701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer sapUshellApplicationPage sapUShellApplicationContainerShiftedIframe sapUshellDefaultBackground</value>
      <webElementGuid>3d3658e6-9d67-4868-b34d-34d99110776b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>07009fa1-64f2-472b-9bb0-f07c2aaa1b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-SalesOrder-create-iframe&quot;)</value>
      <webElementGuid>39f8529e-64a6-4ad8-ac8d-1951562ae2f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-SalesOrder-create-iframe']</value>
      <webElementGuid>00e63005-05db-4f53-8c47-79ed4bc1b898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-SalesOrder-create']/iframe</value>
      <webElementGuid>f0d45c8c-92ef-41a7-94fe-22967ff973c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UT'])[1]/following::iframe[1]</value>
      <webElementGuid>54409ff7-a890-488f-ae6e-5473988e988b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Topics'])[1]/preceding::iframe[2]</value>
      <webElementGuid>e6665de2-443d-4dc1-858d-0f89ea7e03f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d99816bd-837a-4a28-bf49-26425658f183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'application-SalesOrder-create-iframe' and @id = 'application-SalesOrder-create-iframe' and @title = 'Application']</value>
      <webElementGuid>6ad8d301-052e-4b1e-bf81-182df1791a46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
