<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S_InputField</name>
   <tag></tag>
   <elementGuidId>7976b591-0875-4585-866a-e1276a2c72e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:1::0:21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aed674bb-85c7-4287-85df-2777721d45b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1::0:21</value>
      <webElementGuid>71fb38fc-c9e9-4fbf-a786-27e1d2e934a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>db1e8072-45b3-409f-8631-73fc56ccc4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;5&quot;:&quot;10&quot;,&quot;7&quot;:true,&quot;11&quot;:&quot;NUMERIC&quot;,&quot;13&quot;:&quot;S&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;17&quot;:false,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/subSUBSCREEN_HEADER:SAPMV45A:4013/txtVBAP-POSNR&quot;,&quot;Type&quot;:&quot;GuiTextField&quot;,&quot;maxlen&quot;:6,&quot;focusable&quot;:&quot;X&quot;},&quot;22&quot;:&quot;pstxt&quot;,&quot;29&quot;:&quot;M0:46:1::0:0&quot;}</value>
      <webElementGuid>ce181f22-5a10-46d7-aca6-537c99e9a000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;ListAccess&quot;:[{},{}],&quot;DoubleClick&quot;:[{},{&quot;1&quot;:&quot;action/2&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>d324e23e-b0cd-4446-8282-91ae3c9c02df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint</name>
      <type>Main</type>
      <value>{&quot;WebAssistant&quot;:{&quot;id&quot;:{&quot;id&quot;:&quot;wnd[0]/usr/subSUBSCREEN_HEADER:SAPMV45A:4013/txtVBAP-POSNR&quot;,&quot;dynp&quot;:&quot;SAPMV45A:4003:VA03&quot;,&quot;name&quot;:&quot;VBAP-POSNR&quot;}}}</value>
      <webElementGuid>0979d73f-a20e-4daf-840e-7d89190adf3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d507d93-c0d3-4f1d-80cd-c902171b1d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>9c8a5040-dfc1-4a20-96e9-0dc74d8f9ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>3fb9978e-af8b-4839-bb47-b4bcd697d741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>25804fea-5a2e-485d-9cbf-b0f181b1bbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>e8ea2b74-ca60-4ec2-8b1f-e3b0085673e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7fabb036-7ca3-419e-b8b4-0b8d9e82af33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7edd9d5a-e502-4cdb-86d1-4e6d77a52eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sales Document Item</value>
      <webElementGuid>d49e9895-efcb-4034-8339-b165d1e12849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>8847b5db-cb8b-4ae8-819a-b8cff7d98a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>dd78d229-8964-4aac-80e8-d0f90aee2277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8eec25fb-f9d1-4cf6-9398-81b384391a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>409fbd16-b831-440f-a7ad-2e2fe62be545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>M0:46:1::0:0</value>
      <webElementGuid>eb654e7e-d7bd-449c-8bc0-e2124684e739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>893d9753-51bd-411b-83f8-fa28b28f6d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1::0:21&quot;)</value>
      <webElementGuid>7a13e799-2c3c-41b5-9f01-064773cf044d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Display Standard Order 183427 Item Data/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>fdaf035b-51fb-4a16-b783-8065331b9d5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:1::0:21']</value>
      <webElementGuid>57d6b12e-456c-4a19-8ab2-1493db842608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:1::0:21-r']/tbody/tr/td/input</value>
      <webElementGuid>61bd14ce-bb04-43ff-9806-bb068502a263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::input[1]</value>
      <webElementGuid>43b9b6e0-687f-4d2f-b48a-f2cccc6d3cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I'])[1]/preceding::input[1]</value>
      <webElementGuid>a7b05b1a-996f-464e-b0b9-06c36127c9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>b8e1ff1b-1a68-41b6-bba7-3e1345611123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:1::0:21' and @type = 'text' and @title = 'Sales Document Item' and @name = 'InputField']</value>
      <webElementGuid>08c795a8-6e34-4651-8398-3fcbd0cd9fae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
