<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_concat(, , 26, , , ,  In-Home Exercise_e253c4</name>
   <tag></tag>
   <elementGuidId>7945e892-cd05-40c0-ae51-a0b8aff67edc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:2-prevLeft']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b973ff83-5044-48a8-95aa-15ac6fc8bbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>SCROLL_TO_PREVIOUS_ITEMS</value>
      <webElementGuid>060b3d0c-0c6e-41c7-88c5-585350ec10a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--button lsTbsPgPrevLeftDisp lsTbsv6-PageToPrevOn</value>
      <webElementGuid>a5cc68bd-6fd4-49fd-8919-bd8b21dedb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>384f09d3-20a4-465b-a733-8fa41fe05323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>23c2db20-e340-4da3-ae44-13f4411979bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2-prevLeft</value>
      <webElementGuid>1cd4d0b9-3819-4dd7-9bcd-605efff18325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2-prevLeft&quot;)</value>
      <webElementGuid>8a30a642-ebbf-43ba-9da0-d2ac975397ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Display Standard Order 183427 Item Data/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>2c610bea-ee0d-4741-a39c-70692caa72e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:2-prevLeft']</value>
      <webElementGuid>44aa5e38-0a5b-4eb0-b727-19825de0a476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:2']/tbody/tr/td/table/tbody/tr/td/span</value>
      <webElementGuid>e7d5f26c-b441-4762-b5c6-7d0268bd4f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', '26', '&quot;', '', '&quot;', ' In-Home Exercise Bike', '&quot;', '')])[2]/following::span[1]</value>
      <webElementGuid>e72a45ee-9138-4a64-83cc-4c00481f1887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', '26', '&quot;', '', '&quot;', ' In-Home Exercise Bike', '&quot;', '')])[1]/following::span[4]</value>
      <webElementGuid>50c7ebad-17c8-40f5-ad9f-a15115508532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales A'])[1]/preceding::span[1]</value>
      <webElementGuid>b8d6162d-b0a6-40d5-8731-7c42df494d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales B'])[1]/preceding::span[1]</value>
      <webElementGuid>c2c435b9-43f4-4188-a187-6f0e039604ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/span</value>
      <webElementGuid>a0d1d5dc-0ced-4d5a-9cf7-d8e55476029f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:2-prevLeft']</value>
      <webElementGuid>d1b99f0c-8393-4ada-942b-fec712dbf0ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
