<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Additional data B_M0462-next</name>
   <tag></tag>
   <elementGuidId>c2cca916-e835-487a-89b0-e6d5dd8a1a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:2-next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51c690e3-651c-40de-9e92-cc19538b688f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>SCROLL_TO_NEXT_ITEMS</value>
      <webElementGuid>f8d795e1-2fd1-408c-8f20-b4e714b5b94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--button lsMirrorRtl lsTbsv6-PageToNextOn</value>
      <webElementGuid>4e95a38f-2d5c-4161-b0f3-fb9e317c9783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2-next</value>
      <webElementGuid>6f14f45e-f9d5-4be5-a044-be9864455657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2-next&quot;)</value>
      <webElementGuid>127f59d6-0d1e-4d63-9be2-6da528b53ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Display Standard Order 183427 Item Data/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>65653d59-e5c3-4f14-ba0d-7a96319df6a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:2-next']</value>
      <webElementGuid>5a1bd3dd-ae9c-4e51-90ee-39f21cf58a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:2']/tbody/tr/td/table/tbody/tr/td[3]/span[2]</value>
      <webElementGuid>44e5e4ea-8130-4065-b034-2ee8682552a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional data B'])[1]/following::span[2]</value>
      <webElementGuid>f6a434a5-8172-49ac-924e-3f1b4f16b51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional data A'])[1]/following::span[2]</value>
      <webElementGuid>dc451ab2-d802-4822-a88e-c0d69bc06f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Quantity and Delivery Date'])[1]/preceding::span[3]</value>
      <webElementGuid>674efa8d-38c7-4bbd-8299-3d48678002d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span[2]</value>
      <webElementGuid>a669ae3d-1b2a-41ad-a6fc-8383a1bb40dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:2-next']</value>
      <webElementGuid>c1f41763-b6c8-4ed1-b950-33ab29882b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
