<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div5div2iframe1_c-8geh0ohto0h5</name>
   <tag></tag>
   <elementGuidId>29da26e9-496a-4453-b144-1f5616f3f2ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-ig3bpmdrraqx&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-ig3bpmdrraqx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e1d8299f-8f28-4449-bd0e-28b433d1f9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>39e9705f-b2a5-49e7-b957-3494bcf8f52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/enterprise/bframe?hl=en&amp;v=NZrMWHVy58-S9gVvad9HVGxk&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI</value>
      <webElementGuid>0139a0bc-6881-4c78-8b3f-ee24ad0e076a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-ig3bpmdrraqx</value>
      <webElementGuid>734bbc6a-9d5e-4c1f-babb-fda545c8526b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48a571d6-3382-450b-8238-d30420ce7157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>953d532a-90b5-4503-9c53-8b1d60762a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>173860d8-05ef-4a8b-babf-8b32f02da50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[5]/div[2]/iframe[1]</value>
      <webElementGuid>b15f5533-0c9e-4f02-87aa-1447b5130af0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-ig3bpmdrraqx']</value>
      <webElementGuid>0cd634cd-03fe-4c69-86ec-bcb9c83efddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>95c7a817-b42e-4702-bd55-75bfedc602c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'https://www.recaptcha.net/recaptcha/enterprise/bframe?hl=en&amp;v=NZrMWHVy58-S9gVvad9HVGxk&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI' and @name = 'c-ig3bpmdrraqx']</value>
      <webElementGuid>63fc214e-68f9-41ca-a998-99b30ddf27b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-8geh0ohto0h5']</value>
      <webElementGuid>05099051-cd4b-4525-9992-00d7ce79ac4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'https://www.recaptcha.net/recaptcha/enterprise/bframe?hl=en&amp;v=NZrMWHVy58-S9gVvad9HVGxk&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI' and @name = 'c-8geh0ohto0h5']</value>
      <webElementGuid>0bd59824-4add-4722-b7fc-32d843380bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
