<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>17ee277f-bc04-4091-8262-fca5dcc906a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>305c2c25-54cb-4878-9279-f19342d0dd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>2ea8f4be-3bb5-4d93-8b00-3fd23efdc5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRHHcxHKSS7yCICzwF8zox2Cbkt4oTrE0FGLW_Z3Xc6Crur0RG1l-IRkZ_FZIAnaOFCsu7kHY7MhUwOntWqisLc4KW1gWRTQJp9RcL4nBeVNrVootxRVLKSS1MrHxoZj14gIsV20zsZPKnQl7m22efzel-MP2x2Ybn-X2IIqXcJX83DaNxG41aIfmp6ozXbIy5HhhEb1YRqlVpZzzAKzaSIQU4DJGtl9zIyG_yezngyZ4DRDQqs&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI&amp;id=2</value>
      <webElementGuid>567225c1-4a7f-4631-aa79-8fa5a3b8a85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>71965623-4a80-4991-802a-0c5af9e6e9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SAP Universal ID/iframe_html1body1div5div2iframe1_c-8geh0ohto0h5</value>
      <webElementGuid>0bf7fff5-2a5a-4834-a043-48220fd631fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>54075c89-f4d8-485b-999e-5efbafd57062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRHHcxHKSS7yCICzwF8zox2Cbkt4oTrE0FGLW_Z3Xc6Crur0RG1l-IRkZ_FZIAnaOFCsu7kHY7MhUwOntWqisLc4KW1gWRTQJp9RcL4nBeVNrVootxRVLKSS1MrHxoZj14gIsV20zsZPKnQl7m22efzel-MP2x2Ybn-X2IIqXcJX83DaNxG41aIfmp6ozXbIy5HhhEb1YRqlVpZzzAKzaSIQU4DJGtl9zIyG_yezngyZ4DRDQqs&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI&amp;id=2')])[9]</value>
      <webElementGuid>9e121713-9a8b-4fdf-a4c7-4c2776124b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>08f2112c-41df-4075-8df2-fc292534355e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRHHcxHKSS7yCICzwF8zox2Cbkt4oTrE0FGLW_Z3Xc6Crur0RG1l-IRkZ_FZIAnaOFCsu7kHY7MhUwOntWqisLc4KW1gWRTQJp9RcL4nBeVNrVootxRVLKSS1MrHxoZj14gIsV20zsZPKnQl7m22efzel-MP2x2Ybn-X2IIqXcJX83DaNxG41aIfmp6ozXbIy5HhhEb1YRqlVpZzzAKzaSIQU4DJGtl9zIyG_yezngyZ4DRDQqs&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI&amp;id=2']</value>
      <webElementGuid>deae6234-615b-4663-b162-0f1b441cf840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>34cdcc85-735e-44ba-9ac5-1aaf11f3da66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRFCVVYBvXDLCWK1n5RgImY261XjXo9FF-OjAJBJqbxRO3SKe1ruhg60g6sOjlmdb-JCdGTxteWfho90vVnH2j6Kfh-5HLlH3TbKjGUSY06CdURNM15yYBGomHTQe5Qn8jJIcNYfErjzy6ZLvGARx8Kz1h4V_jDaHIVjipBbkU0LmUfivYFMez1T8QRjpKbkMqhT6wnG0EbAroryblF2Q7AcqmQEsOGGsEAecEXq3s6EgEvxqNg&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI&amp;id=2')])[6]</value>
      <webElementGuid>eabb5421-ef5a-4d60-aa97-67c3c520b52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>3335a5ba-9d50-49a4-bca1-51c75aa4bcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRFCVVYBvXDLCWK1n5RgImY261XjXo9FF-OjAJBJqbxRO3SKe1ruhg60g6sOjlmdb-JCdGTxteWfho90vVnH2j6Kfh-5HLlH3TbKjGUSY06CdURNM15yYBGomHTQe5Qn8jJIcNYfErjzy6ZLvGARx8Kz1h4V_jDaHIVjipBbkU0LmUfivYFMez1T8QRjpKbkMqhT6wnG0EbAroryblF2Q7AcqmQEsOGGsEAecEXq3s6EgEvxqNg&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI&amp;id=2']</value>
      <webElementGuid>633f5852-aff1-4765-85e5-d0be5f9858a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
