<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>84f31353-d2bf-46cb-aad2-61651955f16f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6c1f9563-a627-4e39-bab0-4d4ecf77afd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>74eb932d-51c8-4ed7-92ef-673c434e657e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRHHcxHKSS7yCICzwF8zox2Cbkt4oTrE0FGLW_Z3Xc6Crur0RG1l-IRkZ_FZIAnaOFCsu7kHY7MhUwOntWqisLc4KW1gWRTQJp9RcL4nBeVNrVootxRVLKSS1MrHxoZj14gIsV20zsZPKnQl7m22efzel-MP2x2Ybn-X2IIqXcJX83DaNxG41aIfmp6ozXbIy5HhhEb1YRqlVpZzzAKzaSIQU4DJGtl9zIyG_yezngyZ4DRDQqs&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI</value>
      <webElementGuid>c1e7a95f-6e5b-46cf-85ba-fe92a9e680e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>92b326b2-205a-4a09-b95b-26480ff11b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SAP Universal ID/iframe_html1body1div5div2iframe1_c-8geh0ohto0h5</value>
      <webElementGuid>641776bb-d795-4fc3-882f-7691363cc59c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[4]/div/div/img</value>
      <webElementGuid>7a24b6ef-b1fb-41a8-91e0-4164db9b5389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRHHcxHKSS7yCICzwF8zox2Cbkt4oTrE0FGLW_Z3Xc6Crur0RG1l-IRkZ_FZIAnaOFCsu7kHY7MhUwOntWqisLc4KW1gWRTQJp9RcL4nBeVNrVootxRVLKSS1MrHxoZj14gIsV20zsZPKnQl7m22efzel-MP2x2Ybn-X2IIqXcJX83DaNxG41aIfmp6ozXbIy5HhhEb1YRqlVpZzzAKzaSIQU4DJGtl9zIyG_yezngyZ4DRDQqs&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI')])[8]</value>
      <webElementGuid>cad408ba-f11e-4b44-b5d5-a6728dbcd09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/div/img</value>
      <webElementGuid>1775cc6f-807a-4b24-ac0f-b985da6d0abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRHHcxHKSS7yCICzwF8zox2Cbkt4oTrE0FGLW_Z3Xc6Crur0RG1l-IRkZ_FZIAnaOFCsu7kHY7MhUwOntWqisLc4KW1gWRTQJp9RcL4nBeVNrVootxRVLKSS1MrHxoZj14gIsV20zsZPKnQl7m22efzel-MP2x2Ybn-X2IIqXcJX83DaNxG41aIfmp6ozXbIy5HhhEb1YRqlVpZzzAKzaSIQU4DJGtl9zIyG_yezngyZ4DRDQqs&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI']</value>
      <webElementGuid>8a27bbb3-ef5b-41b0-ab66-e0bb2390f2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>7092ff3c-07bc-42f0-91fa-aaeda917e1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRFCVVYBvXDLCWK1n5RgImY261XjXo9FF-OjAJBJqbxRO3SKe1ruhg60g6sOjlmdb-JCdGTxteWfho90vVnH2j6Kfh-5HLlH3TbKjGUSY06CdURNM15yYBGomHTQe5Qn8jJIcNYfErjzy6ZLvGARx8Kz1h4V_jDaHIVjipBbkU0LmUfivYFMez1T8QRjpKbkMqhT6wnG0EbAroryblF2Q7AcqmQEsOGGsEAecEXq3s6EgEvxqNg&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI')])[10]</value>
      <webElementGuid>96402a86-6731-4ff5-aea6-c3e32acce0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>b18b5828-6377-43e1-87fc-fb23fee27b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.recaptcha.net/recaptcha/enterprise/payload?p=06AKH6MRFCVVYBvXDLCWK1n5RgImY261XjXo9FF-OjAJBJqbxRO3SKe1ruhg60g6sOjlmdb-JCdGTxteWfho90vVnH2j6Kfh-5HLlH3TbKjGUSY06CdURNM15yYBGomHTQe5Qn8jJIcNYfErjzy6ZLvGARx8Kz1h4V_jDaHIVjipBbkU0LmUfivYFMez1T8QRjpKbkMqhT6wnG0EbAroryblF2Q7AcqmQEsOGGsEAecEXq3s6EgEvxqNg&amp;k=6LebmqcZAAAAAG6-ZXJaA9MjDqV0erfPGduLV7NI']</value>
      <webElementGuid>a1e0f0d0-5560-4fbb-8928-2d1024e2a263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
