<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Req. Deliv.DateDeliver.PlantComplete Dl_cbc92d</name>
   <tag></tag>
   <elementGuidId>e3d5a14b-5552-40f0-823a-70141f0ebab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:2:3B256:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b0af142-0eda-4275-99b4-d3f05c251e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2:3B256:1</value>
      <webElementGuid>4260975b-a0dc-4d7a-a47e-8b280eb95a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>RL</value>
      <webElementGuid>5e6395cf-3d78-4a8a-9707-2035163f3eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:4.00,&quot;2&quot;:1.25,&quot;4&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440&quot;,&quot;Type&quot;:&quot;GuiScrollContainer&quot;},&quot;6&quot;:&quot;AUTO&quot;}</value>
      <webElementGuid>bc3f5765-9a73-42a7-86a1-9d1b297abea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Scroll&quot;:[{},{}]}</value>
      <webElementGuid>2a091360-7a35-4d76-a345-f4e4de321269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bnoposrefcontainer</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>9f779efc-da1c-4127-9070-2262a45df441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a2e37d51-ee26-40f6-8eb5-396ff8abdc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsRasterLayout  lsRL--relative lsRL--scrollingmode-auto</value>
      <webElementGuid>f39ac3a5-f33d-40d5-83e4-e2b70044a8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Req. Deliv.DateDeliver.Plant:Complete Dlv.Total WeightDelivery BlockVolumeBilling BlockPricing DatePyt TermsInco. VersionIncotermsInco. Location1Inco. Location2Order ReasonSales Area//Dom. Sales Org US, Direct Sales, Product Division 00</value>
      <webElementGuid>035ed771-34fe-40e0-93a5-4b2807ce901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2:3B256:1&quot;)</value>
      <webElementGuid>e8d04868-b47b-4880-b96d-67b197004da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Create Standard Order Overview/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>a7abab00-1871-403a-82be-3c898984d599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2:3B256:1']</value>
      <webElementGuid>0e2c183e-64e1-44c2-984c-afb1920db471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u33F0']/div</value>
      <webElementGuid>410fd8af-1b79-4ad6-b50c-50e1a72f1c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason for Rejection'])[1]/following::div[7]</value>
      <webElementGuid>e180a1bb-0acf-4d27-aa81-99491d97f2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping'])[1]/following::div[10]</value>
      <webElementGuid>39652feb-a512-4e61-a466-726ff3b7575d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/div/div/div/div/div</value>
      <webElementGuid>d5ae8dd0-89aa-4a66-ab54-0503d4fb79c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:2:3B256:1' and (text() = 'Req. Deliv.DateDeliver.Plant:Complete Dlv.Total WeightDelivery BlockVolumeBilling BlockPricing DatePyt TermsInco. VersionIncotermsInco. Location1Inco. Location2Order ReasonSales Area//Dom. Sales Org US, Direct Sales, Product Division 00' or . = 'Req. Deliv.DateDeliver.Plant:Complete Dlv.Total WeightDelivery BlockVolumeBilling BlockPricing DatePyt TermsInco. VersionIncotermsInco. Location1Inco. Location2Order ReasonSales Area//Dom. Sales Org US, Direct Sales, Product Division 00')]</value>
      <webElementGuid>476ee713-0df7-4f14-aeab-6bce32616f61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
