<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(, , undefined, , )_applicatio_2e7af2</name>
   <tag></tag>
   <elementGuidId>b4583712-ded6-4abe-bb6f-901772f921e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-SalesOrder-create-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-SalesOrder-create-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>873cf919-02e8-451b-96d0-afed0b721a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>3de68613-c479-4c32-8fce-09f7cb0590dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>f5b0fea0-c176-4dd4-878e-d1e277433914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>569f380c-0858-4ce5-899b-883de50d7e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=T04;~service=3200?~transaction=%2AVAX1_VBTYP+DYNP_OKCODE%3DENT2%3BP_TRVOG%3D0%3BP_VBTYP%3DC&amp;sap-client=100&amp;sap-language=EN&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=sap_horizon&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-touch=0&amp;sap-ushell-timeout=0&amp;sap-shell=FLP1.102.12</value>
      <webElementGuid>07594b70-45aa-417b-b6f0-3d8fe17b8e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>032d3aa9-3c1c-4cf9-8333-90e3f6c98011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer sapUshellApplicationPage sapUShellApplicationContainerShiftedIframe sapUshellDefaultBackground</value>
      <webElementGuid>d35b6a70-c7db-4fbf-a82b-c0869e86cc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>c5cf77f8-aa2a-4f19-a667-9db7d21145bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-SalesOrder-create-iframe&quot;)</value>
      <webElementGuid>845abef0-aa9c-4e62-94db-c76f8caf1d70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-SalesOrder-create-iframe']</value>
      <webElementGuid>6f805d6d-6bf9-4f06-8329-68ad28e8b5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-SalesOrder-create']/iframe</value>
      <webElementGuid>4b02dc70-d075-4ee4-a346-933e2af060e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2176c621-80f8-48fb-8285-fe60402ccc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'application-SalesOrder-create-iframe' and @id = 'application-SalesOrder-create-iframe' and @title = 'Application']</value>
      <webElementGuid>b3e7998e-baa3-420d-8c2e-573caa20bfa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
