<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_17100007</name>
   <tag></tag>
   <elementGuidId>7ac8c7be-f48b-4498-a34a-5bc53da293ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lsListbox__highlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:1:1::0:17_TALB-item-0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5514b53-be33-4fd0-8c97-cf135f99c50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsListbox__highlight</value>
      <webElementGuid>a665e9a9-5caf-4633-9d74-693fc867eb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17100007</value>
      <webElementGuid>0dd5781f-a9b8-425a-8e4f-737fc4f66cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:1::0:17_TALB-item-0&quot;)/span[@class=&quot;lsListbox__highlight&quot;]</value>
      <webElementGuid>a1282d4f-e642-440f-9152-6b24fe74b968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Create Standard Order Overview/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>d1e27a41-3445-4116-a74b-c093e39fb261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:1::0:17_TALB-item-0']/span</value>
      <webElementGuid>bb0b7dc3-d039-43a2-b53c-b0069d7363ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empty'])[2]/following::span[1]</value>
      <webElementGuid>2b381215-f774-4808-a16d-2814c2b37176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BARREL'])[1]/preceding::span[1]</value>
      <webElementGuid>781c18f1-7d95-4028-8c10-49fc6271fa81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US'])[1]/preceding::span[1]</value>
      <webElementGuid>2bde9a30-1b9a-4a09-8e22-3859227c06a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='17100007']/parent::*</value>
      <webElementGuid>edd630a2-7f49-44f5-bf62-56e43ea098fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/span</value>
      <webElementGuid>50638982-13bf-472b-bdea-3fe89f7aca8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '17100007' or . = '17100007')]</value>
      <webElementGuid>7d39e997-fbad-4738-80f2-d5d01bc07cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
