<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UT</name>
   <tag></tag>
   <elementGuidId>ed59595d-1964-431e-ae21-d82e16babf8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shell-header-hdr-end</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shell-header-hdr-end']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ef9cc34-dcff-4fa6-8076-1a92ac8d50ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shell-header-hdr-end</value>
      <webElementGuid>177a608c-6eb6-4546-a0c0-d5b21976114c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUshellShellHeadEnd</value>
      <webElementGuid>28f7ad12-7ab0-4df8-b28b-3a77d973975a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UT</value>
      <webElementGuid>fd2c1415-26b1-415a-8761-1982a141577f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shell-header-hdr-end&quot;)</value>
      <webElementGuid>83f08abc-b583-4bbd-854e-5984854f101f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='shell-header-hdr-end']</value>
      <webElementGuid>1c01e113-0e0b-42e1-ae01-525fcf50b6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='shell-header']/div[4]</value>
      <webElementGuid>11bbaaeb-1482-40c4-a6c4-c7478d3c26e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::div[1]</value>
      <webElementGuid>b6d6bb10-c35b-4545-b7c5-668b22d64fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::div[5]</value>
      <webElementGuid>ba7d6aed-dd44-49fa-8b89-75f98f434e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div[4]</value>
      <webElementGuid>d9e522c8-8a69-45cb-bc6f-c14640996e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'shell-header-hdr-end' and (text() = 'UT' or . = 'UT')]</value>
      <webElementGuid>507efcdf-7992-43b6-932b-b29b39cf4a10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
