<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Trial Center_shell-header-hdr-search-container</name>
   <tag></tag>
   <elementGuidId>af545d98-9749-46db-8fec-d3efe59f1c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shell-header-hdr-search-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shell-header-hdr-search-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ed3ba9c-d925-49c2-8e3d-531246f1b7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shell-header-hdr-search-container</value>
      <webElementGuid>ae94d5c0-5071-490c-84ab-8817bc7fddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUshellShellHeadSearchContainer</value>
      <webElementGuid>ea268a4b-07c1-4bdc-ae10-937091c75883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shell-header-hdr-search-container&quot;)</value>
      <webElementGuid>557f4f55-44e5-4367-83b9-268e55929416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='shell-header-hdr-search-container']</value>
      <webElementGuid>7f941b0b-4e69-4f15-be31-d822a89a9db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='shell-header']/div[3]</value>
      <webElementGuid>344c5f30-d13b-45d8-9c9e-9977d2439d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trial Center'])[2]/following::div[1]</value>
      <webElementGuid>742ab04f-08cc-415e-a5f5-d95686e6ee14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[2]</value>
      <webElementGuid>629dce7f-c8d3-4860-8c67-e1ec6a6f1ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[2]</value>
      <webElementGuid>7e937882-7ff6-4ae1-802e-37832a7eeffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UT'])[1]/preceding::div[2]</value>
      <webElementGuid>935220df-0109-4d0a-bccc-cd87f5ffc37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div[3]</value>
      <webElementGuid>ae26897f-b347-4f1f-9c17-186609bdcf1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'shell-header-hdr-search-container']</value>
      <webElementGuid>5d22ce63-d8e6-424d-a35d-4a52fc64f4f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
