<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(, , undefined, , )_applicatio_2e7af2</name>
   <tag></tag>
   <elementGuidId>6fc1befa-a02b-45a9-8598-4fe1cd649837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-SalesOrder-create-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-SalesOrder-create-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ab60ea31-c960-4f4d-8a17-2bb920b8ba77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>b66c4c30-3fb2-456e-a495-5a7b77865217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>f7da5d61-0b22-4429-b5a3-4930416761e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>2576faa7-d010-47dd-8c4e-13fba2eeed55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=SUY;~service=3200?~transaction=%2AVAX1_VBTYP+DYNP_OKCODE%3DENT2%3BP_TRVOG%3D0%3BP_VBTYP%3DC&amp;sap-client=100&amp;sap-language=EN&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=sap_horizon&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-touch=0&amp;sap-ushell-timeout=0&amp;sap-shell=FLP1.108.19</value>
      <webElementGuid>6f267a68-e560-4c45-a14b-c202142df3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>c3a30ffd-2494-41f0-bb1b-78e8a8b5183b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>a7851218-7d77-480d-bede-f41b3ed697c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>ba6a24e0-8474-4ef9-98c2-a99d02ae5ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-SalesOrder-create-iframe&quot;)</value>
      <webElementGuid>83262c5c-0d91-4858-bacf-6c19fc301f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8ef992c8-6e5b-440a-bdb5-56217bc3e13c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-SalesOrder-create-iframe']</value>
      <webElementGuid>4462c112-a13a-4e71-95b4-2fd0085059a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-SalesOrder-create']/iframe</value>
      <webElementGuid>1202b298-a5ba-49cb-a1c9-4df85bbc291c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7470711a-9998-4989-96e4-b27c9123d1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-SalesOrder-create-iframe' and @name = 'application-SalesOrder-create-iframe' and @title = 'Application']</value>
      <webElementGuid>36c89a22-e679-4c46-b022-9612245b85fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'application-SalesOrder-create-iframe' and @id = 'application-SalesOrder-create-iframe' and @title = 'Application']</value>
      <webElementGuid>44bf24a3-54d9-43fa-aa16-424e9af655b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
