<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(, , undefined, , )_applicatio_2e7af2</name>
   <tag></tag>
   <elementGuidId>6fc1befa-a02b-45a9-8598-4fe1cd649837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-SalesOrder-create-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-SalesOrder-create-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3d5543fa-5ce7-4d11-a7f4-d9a1fd7c2862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>2445674c-fe96-422c-92cf-a8db1eec2ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>f73badc7-8717-4017-bb0a-12bf19146ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-SalesOrder-create-iframe</value>
      <webElementGuid>96272763-d3de-433e-b5bd-567820c402f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=T04;~service=3200?~transaction=%2AVAX1_VBTYP+DYNP_OKCODE%3DENT2%3BP_TRVOG%3D0%3BP_VBTYP%3DC&amp;sap-client=100&amp;sap-language=EN&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=sap_horizon&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-touch=0&amp;sap-ushell-timeout=0&amp;sap-shell=FLP1.102.12</value>
      <webElementGuid>5dcfe2f7-3a41-4987-8d73-2dda9e1998c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>17cf5210-85cc-42cd-8b06-ef38a9270396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer sapUshellApplicationPage sapUShellApplicationContainerShiftedIframe sapUshellDefaultBackground</value>
      <webElementGuid>984fb787-515a-43f0-8ad5-65712f5f5d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>aeb91382-c666-44fe-9857-144741e0e7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-SalesOrder-create-iframe&quot;)</value>
      <webElementGuid>24f04be5-2551-49f1-8c8b-03dc544e1ccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-SalesOrder-create-iframe']</value>
      <webElementGuid>7bc6faa2-a8c8-4cb3-86ef-cd0af50d84a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-SalesOrder-create']/iframe</value>
      <webElementGuid>eaee2e65-1ac4-49a9-ae81-d5727598e99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0bacef8f-457b-4315-9b3a-2b7a16e7be23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'application-SalesOrder-create-iframe' and @id = 'application-SalesOrder-create-iframe' and @title = 'Application']</value>
      <webElementGuid>44bf24a3-54d9-43fa-aa16-424e9af655b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
