<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10</name>
   <tag></tag>
   <elementGuidId>75bd0588-0938-40b8-bacc-05e0725c6bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tbl9[1,3]_c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0bb3f56c-e787-4692-9a3d-653fedd72ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a5cff898-976b-4b89-ac48-718ab841b795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>18d13a2b-830d-436b-ae87-665fd87c0165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4c0acfab-d36d-4990-b5e9-a30e1a060971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbl9[1,3]_c</value>
      <webElementGuid>e5ccc6a7-2255-4d88-a656-57ca94840713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>08e0b1fe-dd2b-45b5-b231-af4289ec8c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;5&quot;:&quot;10&quot;,&quot;7&quot;:true,&quot;11&quot;:&quot;NUMERIC&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;17&quot;:false,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL_U_ERF_AUFTRAG/txtRV45A-KWMENG[2,0]&quot;,&quot;Type&quot;:&quot;GuiTextField&quot;,&quot;ctmenu&quot;:true,&quot;halign&quot;:&quot;r&quot;,&quot;maxlen&quot;:19,&quot;focusable&quot;:&quot;X&quot;},&quot;25&quot;:&quot;FILL_FIXED_LAYOUT&quot;}</value>
      <webElementGuid>056c9334-35c4-45cb-b090-bf52c7e7fd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;ListAccess&quot;:[{},{}]}</value>
      <webElementGuid>2bd6c358-25fe-47ba-a7aa-6542c0d76a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>f48b8153-0b76-4754-8ac2-88ce68587072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>fdee8048-8388-412f-ba7f-72f22a6c2a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>2434d5fc-572a-42e6-8ba1-e85de5ed5bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>8c0e994d-6d58-40f0-8998-7b4076168750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint</name>
      <type>Main</type>
      <value>{&quot;WebAssistant&quot;:{&quot;id&quot;:{&quot;id&quot;:&quot;wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL_U_ERF_AUFTRAG/txtRV45A-KWMENG[2,0]&quot;,&quot;dynp&quot;:&quot;SAPMV45A:4001:VA03&quot;,&quot;name&quot;:&quot;RV45A-KWMENG&quot;}}}</value>
      <webElementGuid>402d5224-1d1a-46be-b176-5acbbe8a8662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f775f105-fe39-4ac0-ad2e-7317a7ca2256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl9[1,3]_c&quot;)</value>
      <webElementGuid>1bf8aafe-3a84-4ade-8156-788756e5f46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Display Sales Order - VA03/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>b29f72c0-381c-4ef0-8ff2-e7eed2ce711f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='tbl9[1,3]_c']</value>
      <webElementGuid>02a1e3f9-6c62-40c2-b836-5c1d3ef18e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='tbl9[1,3]_c-r']/span</value>
      <webElementGuid>69ae8c25-071f-493b-9c3c-2b94f47026a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MZ-FG-26XR1'])[1]/following::span[3]</value>
      <webElementGuid>1058a2d1-7937-411d-be19-d6c430573779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To select a row, press the spacebar.'])[1]/following::span[7]</value>
      <webElementGuid>b8d0da32-e804-4bc5-8a48-21167eb929ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC'])[1]/preceding::span[2]</value>
      <webElementGuid>9d340eb1-9549-41e4-a9ca-1f382b5b1d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', '26', '&quot;', '', '&quot;', ' In-Home Exercise Bike', '&quot;', '')])[1]/preceding::span[6]</value>
      <webElementGuid>5cbfd2dd-db06-4a19-96ba-961c8e9914a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/span/span</value>
      <webElementGuid>232c1a52-caef-4af3-a22c-bd9f0dbd56cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'tbl9[1,3]_c' and @name = 'InputField' and (text() = '10' or . = '10')]</value>
      <webElementGuid>bf7a8e91-e42d-46b6-aac4-ed22bcd515c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
