<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ExitHelp</name>
   <tag></tag>
   <elementGuidId>4d2b92ea-bab8-4e07-ac26-ff464d471f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@title='Exit (Enter)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ade0faa0-dc6f-4773-b86d-0470239568d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>toolbar</value>
      <webElementGuid>401a4efa-6745-4c0f-9c8a-c46f83d14ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M1:37-itms</value>
      <webElementGuid>f8693ead-4f53-47e7-9212-79cd37ded494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsToolbar--standards-leftItems lsToolbar--noFixedRightItems</value>
      <webElementGuid>fa77c6e5-e180-4dc1-8624-ae356817dcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ExitHelp</value>
      <webElementGuid>5b3f1a30-334b-46da-afc4-40adaebb7665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M1:37-itms&quot;)</value>
      <webElementGuid>5d951688-dd9d-4e3a-84fd-ad479e95bde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SAP/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>e8817690-2651-48f1-92f6-0fd2eb92d79d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M1:37-itms']</value>
      <webElementGuid>d853b2a6-b125-41ff-90e4-b68847344d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M1:37']/div</value>
      <webElementGuid>6651c1c2-ee2a-4292-8031-60b2a638aa08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Order 183427 has been saved.'])[1]/following::div[7]</value>
      <webElementGuid>ef2010f4-6b6b-4773-971f-ab1b58e8637c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[12]</value>
      <webElementGuid>508b5696-de91-4e3c-8f7b-d85d50f815f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/div</value>
      <webElementGuid>f465b5e5-d898-44fc-b32d-50f2781d8074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M1:37-itms' and (text() = 'ExitHelp' or . = 'ExitHelp')]</value>
      <webElementGuid>b57f250a-58bd-4eea-80ec-093fadd10e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
