<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Information</name>
   <tag></tag>
   <elementGuidId>77446db2-fcba-4985-b93f-8f5147af5a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SAPMSDYP10_1-ttltxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SAPMSDYP10_1-ttltxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ccdaf3d-d24d-447e-96e7-5e70037fcf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>drag</name>
      <type>Main</type>
      <value>move</value>
      <webElementGuid>35ea7b0c-d631-45af-ae0d-57ca6b5f8031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SAPMSDYP10_1-ttltxt</value>
      <webElementGuid>f2b76a7d-1637-4561-8bbc-ccee7c69a54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>urPWTitleText lsResponsivePaddingLeft</value>
      <webElementGuid>6bf68937-3f37-4a0d-839e-1e3e2edfe24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>0c448650-737f-4fc9-b644-4489a850ea97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Information</value>
      <webElementGuid>50c4e476-a01f-43b7-b78f-8ec2f2fd2b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SAPMSDYP10_1-ttltxt&quot;)</value>
      <webElementGuid>f84df48c-6457-446a-9bf1-0697a2467e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SAP/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>57ccf258-88d5-407f-8b3b-6079dcc91400</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='SAPMSDYP10_1-ttltxt']</value>
      <webElementGuid>87816d40-4b51-4e6c-a7fc-2e4aa2abb449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='SAPMSDYP10_1-ttl']/tbody/tr/td/div</value>
      <webElementGuid>a0975f68-1d6f-415a-a17c-2b3d5c4d3208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment list'])[2]/following::div[8]</value>
      <webElementGuid>9e8d62eb-ba51-413f-99bf-a6d2f1266b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment list'])[1]/following::div[8]</value>
      <webElementGuid>fca09943-3861-4620-a7af-740ee7a216a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Order 183427 has been saved.'])[1]/preceding::div[3]</value>
      <webElementGuid>946abffe-1473-4a3a-b2a3-c4cb318c361d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/div</value>
      <webElementGuid>36bfcccb-322d-476c-844c-f9590a4b7d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'SAPMSDYP10_1-ttltxt' and (text() = 'Information' or . = 'Information')]</value>
      <webElementGuid>a5b0ad93-516d-46f0-b9c9-1792e2f4e7ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
