<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_enu_urPopupWindowBlockLayer</name>
   <tag></tag>
   <elementGuidId>2e5abf37-ec09-48d7-9ece-b9226f387e89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#urPopupWindowBlockLayer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='urPopupWindowBlockLayer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd5a53a7-a0f6-4eb6-b7e0-9a69edfb7397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>urPopupWindowBlockLayer</value>
      <webElementGuid>9d49a30d-8feb-4836-9dda-cf2d4473113d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>986ac531-bc2a-4357-9ed3-af8a89c326a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsBlockLayer</value>
      <webElementGuid>958426d5-18a2-4850-97fe-a6b3f2e32a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;urPopupWindowBlockLayer&quot;)</value>
      <webElementGuid>0e77d937-a1c0-438c-a71c-8da4720382d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SAP/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>65f4e48f-bee6-4898-b7b6-5c78d0acce87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='urPopupWindowBlockLayer']</value>
      <webElementGuid>b5a66d4c-2773-4403-97b6-8ff067f71858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/preceding::div[2]</value>
      <webElementGuid>cfc5177e-d894-4cac-9a4f-c37460ae3c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>83c07d7f-4f9a-4e0a-aa02-20def0c18eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'urPopupWindowBlockLayer']</value>
      <webElementGuid>1049ff7f-7eb0-4352-b79e-e5c9f3f88469</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
