<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Exit</name>
   <tag></tag>
   <elementGuidId>c16dec9f-cff2-4b97-90ef-07a4b531bd44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@title='Exit (Shift F3)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9d3fcab-00bd-4d7a-9d3b-5c5aa747f498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5c14225c-bb32-4123-86bc-0ffb521fdc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M1:50::btn[0]</value>
      <webElementGuid>c131894e-5e5c-4735-bade-7265ab892512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>36fa93ea-eea9-4d4d-9623-bb5629fd2219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Exit&quot;,&quot;2&quot;:&quot;TRANSPARENT&quot;,&quot;4&quot;:&quot;Exit (Enter)&quot;,&quot;18&quot;:&quot;E&quot;,&quot;19&quot;:&quot;ENTER&quot;,&quot;22&quot;:true,&quot;26&quot;:&quot;TOGGLE&quot;,&quot;28&quot;:{&quot;SID&quot;:&quot;wnd[1]/tbar[0]/btn[0]&quot;,&quot;Type&quot;:&quot;GuiButton&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>67dac325-cdc2-4831-9b8e-e3cdbda3e6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;0&quot;:&quot;GuiOkCodeButton&quot;,&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}]}</value>
      <webElementGuid>fea97b15-43d2-41f1-9997-c955c2d84ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint</name>
      <type>Main</type>
      <value>{&quot;WebAssistant&quot;:{&quot;id&quot;:{&quot;id&quot;:&quot;wnd[1]/tbar[0]/btn[0]&quot;,&quot;dynp&quot;:&quot;SAPMSDYP:10:S000&quot;}}}</value>
      <webElementGuid>05bc0cf5-f3f0-4e89-a13d-212ccf95483b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b14dd6a3-8568-4357-a056-7dcb024ec9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Exit (Enter)</value>
      <webElementGuid>2912083f-9d74-42c7-a5e5-1d499939cce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>E</value>
      <webElementGuid>bb5a27de-01c9-427a-81bf-5ed8cdcc0c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>E</value>
      <webElementGuid>8a147184-ad70-4dfc-80db-571e8a0e908d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c342d7e9-cf1f-46fe-a7df-df2761ca1be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d24b24c6-2194-4bab-ac1e-07290d49ea69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urInlineMetricTop urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-transparent lsButton--hoverable</value>
      <webElementGuid>24e61daa-889a-4d68-a220-1d13c0e85285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>M1:50::btn[0]-r</value>
      <webElementGuid>10f55760-6632-40d0-8a80-87bc3b32d71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exit</value>
      <webElementGuid>244631f6-f105-4ad2-8159-04ff9c2015e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M1:50::btn[0]&quot;)</value>
      <webElementGuid>88785c41-4e49-4606-90aa-7129391fd9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SAP/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>333d3c83-64f5-4de7-9823-325c2a982150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M1:50::btn[0]']</value>
      <webElementGuid>55db40cd-6481-4fb2-893f-0e9b7c582414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M1:50::btn[0]-r']/div</value>
      <webElementGuid>daeedd75-5009-4d31-a626-7c85de3402cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Order 183427 has been saved.'])[1]/following::div[8]</value>
      <webElementGuid>d6f2b91d-7790-4d90-8547-07c6b030b77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[13]</value>
      <webElementGuid>e1f66d3b-1df3-4495-829c-9667204ea6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div</value>
      <webElementGuid>d756c28e-3362-409a-89b0-e719593236e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M1:50::btn[0]' and @title = 'Exit (Enter)' and (text() = 'Exit' or . = 'Exit')]</value>
      <webElementGuid>16e4155a-1c4f-4916-ae55-d0e2af04ac11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
