<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Standard Order 183427 has been saved</name>
   <tag></tag>
   <elementGuidId>8254cde0-360a-4cb3-badc-f2021f3158f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M1:46:::0:5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d96c1a6e-7d1d-4be4-820c-bb753de316f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>L</value>
      <webElementGuid>5fce3b4c-9d42-4441-b8f5-3c07b45b9f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;3&quot;:&quot;Standard Order 183427 has been saved.&quot;,&quot;6&quot;:&quot;LIGHT&quot;,&quot;7&quot;:&quot;100%&quot;,&quot;13&quot;:&quot;BEGINOFLINE&quot;,&quot;14&quot;:true,&quot;16&quot;:&quot;ACTIVATE&quot;,&quot;19&quot;:{&quot;SID&quot;:&quot;wnd[1]/usr/txtMESSTXT1&quot;,&quot;Type&quot;:&quot;GuiLabel&quot;,&quot;focusable&quot;:&quot;X&quot;}}</value>
      <webElementGuid>4114c0fe-2a16-443d-bf33-aa9fef4f79be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M1:46:::0:5</value>
      <webElementGuid>380e7692-ce6c-40c0-8caa-510012009e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bhastabstop</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>31cee6ef-e55c-4ae4-af44-3697e2b3d1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8650a2f0-c135-4ab2-a666-335bc1406d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43ef61b6-0f72-4b89-a2b9-4f14ee89fbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsLabel lsLabel--valign lsControl--startaligned  lsLabel--standalone lsLabel--text lsControl--fullwidth lsLabel--wrapping lsLabel--designbar-light</value>
      <webElementGuid>c6f3dd2f-a75a-4805-8c01-04289ee225d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standard Order 183427 has been saved.</value>
      <webElementGuid>0d3bfb7a-27e2-4b66-99c2-1ccbe0deb174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M1:46:::0:5&quot;)</value>
      <webElementGuid>aa306161-75f5-4961-94ec-9df9a2db965d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SAP/iframe_concat(, , undefined, , )_applicatio_2e7af2</value>
      <webElementGuid>0ce16e56-ab08-4663-9ffb-376594319b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M1:46:::0:5']</value>
      <webElementGuid>b406c604-9bce-4cfa-aeb1-744c711bcfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M1:46:::0:5-r']/span</value>
      <webElementGuid>76a1912b-cfbe-46b6-9d46-dd76ceb2384f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::span[4]</value>
      <webElementGuid>653ee844-a8ab-41bb-a4cf-fe31df00f3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment list'])[2]/following::span[7]</value>
      <webElementGuid>6d6cd998-4eb0-4348-a423-f704cc3ec098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/span/span</value>
      <webElementGuid>d657ae25-148d-4944-996c-d095c9f767b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M1:46:::0:5' and (text() = 'Standard Order 183427 has been saved.' or . = 'Standard Order 183427 has been saved.')]</value>
      <webElementGuid>b6c08a41-ffc0-4c94-a78c-0e20ff3a50bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
